Fix/server signal refactor
Granola-Team/onchain-signalling pull request #118
Opened 2022-11-18 06:09 UTC by jenr24G

Refactors the signal processing code from the scope of `construct_responses()` down to be more readable and testable

2022-11-18 19:31 UTC, mxnkarou requested changes
Much more readable - good stuff!
One issue came up - would be great if you could check that out:
It seems like the sorting is not working. Ideally we'd want the signals sorted by timestamp.

2022-11-18 19:44 UTC, jenr24G commented
An antipattern I noticed throughout this refactor, using Option's for delayed initialization. initializing a value to None so that you can have a draft object in state to be finished later makes all the code that has to deal with that Option spaghetti-like and just a plain mess. Use Option's for potential failure, not delayed initialization plz thx bye

2022-11-19 02:08 UTC, mxnkarou requested changes
Sorting looks good!
One thing we'd need to revert is the folder/file structure to reflect the actual endpoints.
Common practice when building REST API's is to keep routes in sync with files.
i.E. in this case the route that is currently handled in `router/api/mod.rs` should be `router/api/keyword.rs`.


And concerning the first comment - let's keep counting settled/unsettled votes.

2022-11-21 18:45 UTC, mxnkarou commented on server/src/processor.rs
>      }
You can match directly on the `ResponseEntity` struct without having to shadow `None` with `stats_option`.

`fn generate_response(self) -> ResponseEntity {
        let stats = self.stats();
        let settled = self
            .current_settled
            .into_iter()
            .map(|(_, v)| v)
            .collect::<Vec<Signal>>();

        ResponseEntity {
            settled,
            unsettled: self.unsettled_signals,
            invalid: self.invalid_signals,
            stats: match stats.yes != 0. && stats.no != 0. {
                true => Some(stats),
                false => None,
            },
        }
    }`

2022-11-21 18:49 UTC, mxnkarou commented on server/src/processor.rs
>      }
And another change would be required on `models/mod.rs - line 73`:
`self.stats = stats` => ` self.stats = Some(stats)`

2022-11-21 18:51 UTC, mxnkarou requested changes

2022-11-21 18:51 UTC, mxnkarou commented on server/src/models/mod.rs
> +        self.stats = stats;
This needs to be `self.stats = Some(stats);`

2022-11-21 18:51 UTC, mxnkarou commented on server/src/processor.rs
> +    }
You can match directly on the struct without shadowing `None` in `stats_option`:
```
fn generate_response(self) -> ResponseEntity {
        let stats = self.stats();
        let settled = self
            .current_settled
            .into_iter()
            .map(|(_, v)| v)
            .collect::<Vec<Signal>>();

        ResponseEntity {
            settled,
            unsettled: self.unsettled_signals,
            invalid: self.invalid_signals,
            stats: match stats.yes != 0. && stats.no != 0. {
                true => Some(stats),
                false => None,
            },
        }
    }

2022-11-21 19:48 UTC, mxnkarou approved these changes

2022-11-21 19:48 UTC, jenr24G commented on client/src/types/components.d.ts
> +  stats: StatsEntity | null;
😏​

2022-11-21 19:49 UTC, jenr24G commented on client/src/types/components.d.ts
> +  stats: StatsEntity | null;
😒​

2022-11-21 19:50 UTC, merged